set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports FX3_CLK]

set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {FX3b[16]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {FX3b[0]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {FX3b[17]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {FX3b[1]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {FX3b[18]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {FX3b[2]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {FX3b[19]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {FX3b[3]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {FX3b[20]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {FX3b[4]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {FX3b[21]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {FX3b[5]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {FX3b[22]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {FX3b[6]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {FX3b[23]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {FX3b[7]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {FX3b[24]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {FX3b[8]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {FX3b[25]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {FX3b[9]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {FX3b[26]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {FX3b[10]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {FX3b[27]}]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {FX3b[11]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {FX3b[28]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {FX3b[12]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {FX3b[29]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {FX3b[13]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {FX3b[30]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {FX3b[14]}]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports {FX3b[31]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {FX3b[15]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports NIRS_MUX_SELB]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports NIRS_MUX_SELA]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports NIRS_ADC_CLKA]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports NIRS_ADC_CLKB]
set_property -dict {PACKAGE_PIN E7 IOSTANDARD LVCMOS33} [get_ports NIRS_ADC_MUX]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {ADCb[0]}]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {ADCb[1]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {ADCb[2]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {ADCb[3]}]

 set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports FPGA_CLK]
#create_clock -period 50 [get_ports FPGA_CLK]

# set_property -dict {PACKAGE_PIN M3	IOSTANDARD LVCMOS33} [get_ports B34_L4_P]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {VAP[0]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {VAP[1]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {VAP[2]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {VAP[3]}]
#set_property -dict {PACKAGE_PIN P2	IOSTANDARD LVCMOS33} [get_ports SPI_SCLK]
#set_property -dict {PACKAGE_PIN R2	IOSTANDARD LVCMOS33} [get_ports SPI_SDO]
#set_property -dict {PACKAGE_PIN R1	IOSTANDARD LVCMOS33} [get_ports SPI_SDI]
#set_property -dict {PACKAGE_PIN T1	IOSTANDARD LVCMOS33} [get_ports nCS]
#set_property -dict {PACKAGE_PIN M4	IOSTANDARD LVCMOS33} [get_ports ERROR_DCS]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports FRAME]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports RUN]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports nRESET]
# set_property -dict {PACKAGE_PIN R3	IOSTANDARD LVCMOS33} [get_ports B34_L11_P]
# set_property -dict {PACKAGE_PIN T3	IOSTANDARD LVCMOS33} [get_ports B34_L11_N]
# set_property -dict {PACKAGE_PIN T4	IOSTANDARD LVCMOS33} [get_ports B34_L12_N]
# set_property -dict {PACKAGE_PIN T5	IOSTANDARD LVCMOS33} [get_ports B34_L12_P]
# set_property -dict {PACKAGE_PIN P5	IOSTANDARD LVCMOS33} [get_ports B34_L13_N]

#set_property -dict {PACKAGE_PIN N5	IOSTANDARD LVCMOS33} [get_ports FPGA_CLK]


# set_property -dict {PACKAGE_PIN U1	IOSTANDARD LVCMOS33} [get_ports B34_L7_P]
# set_property -dict {PACKAGE_PIN V1	IOSTANDARD LVCMOS33} [get_ports B34_L7_N]
# set_property -dict {PACKAGE_PIN U2	IOSTANDARD LVCMOS33} [get_ports B34_L9_P]
# set_property -dict {PACKAGE_PIN V2	IOSTANDARD LVCMOS33} [get_ports B34_L9_N]
#set_property -dict {PACKAGE_PIN U3	IOSTANDARD LVCMOS33} [get_ports SPAD2b[3]]
#set_property -dict {PACKAGE_PIN U4	IOSTANDARD LVCMOS33} [get_ports SPAD2b[2]]
#set_property -dict {PACKAGE_PIN R5	IOSTANDARD LVCMOS33} [get_ports SPAD2b[0]]
#set_property -dict {PACKAGE_PIN R6	IOSTANDARD LVCMOS33} [get_ports SPAD2b[1]]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {SPAD1b[3]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {SPAD1b[2]}]
set_property -dict {PACKAGE_PIN R7 IOSTANDARD LVCMOS33} [get_ports {SPAD1b[1]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS33} [get_ports {SPAD1b[0]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {ADCb[4]}]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS33} [get_ports {ADCb[5]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {ADCb[6]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS33} [get_ports {ADCb[7]}]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports {ADCb[8]}]
set_property -dict {PACKAGE_PIN N6 IOSTANDARD LVCMOS33} [get_ports {ADCb[9]}]
set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVCMOS33} [get_ports {ADCb[10]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports {ADCb[11]}]
set_property -dict {PACKAGE_PIN R8 IOSTANDARD LVCMOS33} [get_ports {ADCb[12]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS33} [get_ports {ADCb[13]}]
#set_property -dict {PACKAGE_PIN M18	IOSTANDARD LVCMOS33} [get_ports UART_RXD]
#set_property -dict {PACKAGE_PIN L18	IOSTANDARD LVCMOS33} [get_ports UART_TXD]
#set_property -dict {PACKAGE_PIN M17	IOSTANDARD LVCMOS33} [get_ports XMOD_E]

set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports LED]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD1b_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD1b_IBUF[1]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD1b_IBUF[2]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD1b_IBUF[3]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD2b_IBUF[0]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD2b_IBUF[1]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD2b_IBUF[2]]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPAD2b_IBUF[3]]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FPGA_CLK_IBUF]





set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.M1PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M2PIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.M0PIN PULLNONE [current_design]

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]
