# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TE0725.xdc

# Block Designs: bd/block1/block1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1 || ORIG_REF_NAME==block1} -quiet] -quiet

# IP: bd/block1/ip/block1_ADC_0_0/block1_ADC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_ADC_0_0 || ORIG_REF_NAME==block1_ADC_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_Blink_0_0/block1_Blink_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_Blink_0_0 || ORIG_REF_NAME==block1_Blink_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_FX3_0_0/block1_FX3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_FX3_0_0 || ORIG_REF_NAME==block1_FX3_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_FrameCounter_0_0/block1_FrameCounter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_FrameCounter_0_0 || ORIG_REF_NAME==block1_FrameCounter_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_VapBuffer_0_0/block1_VapBuffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_VapBuffer_0_0 || ORIG_REF_NAME==block1_VapBuffer_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_clk_wiz_0_0/block1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_clk_wiz_0_0 || ORIG_REF_NAME==block1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_Counter_0_0/block1_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_Counter_0_0 || ORIG_REF_NAME==block1_Counter_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_Counter_1_0/block1_Counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_Counter_1_0 || ORIG_REF_NAME==block1_Counter_1_0} -quiet] -quiet

# IP: bd/block1/ip/block1_Counter_2_0/block1_Counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_Counter_2_0 || ORIG_REF_NAME==block1_Counter_2_0} -quiet] -quiet

# IP: bd/block1/ip/block1_Counter_3_0/block1_Counter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_Counter_3_0 || ORIG_REF_NAME==block1_Counter_3_0} -quiet] -quiet

# IP: bd/block1/ip/block1_xlconcat_0_0/block1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xlconcat_0_0 || ORIG_REF_NAME==block1_xlconcat_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_xlslice_0_0/block1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xlslice_0_0 || ORIG_REF_NAME==block1_xlslice_0_0} -quiet] -quiet

# IP: bd/block1/ip/block1_xlslice_0_1/block1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xlslice_0_1 || ORIG_REF_NAME==block1_xlslice_0_1} -quiet] -quiet

# IP: bd/block1/ip/block1_xlslice_0_2/block1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xlslice_0_2 || ORIG_REF_NAME==block1_xlslice_0_2} -quiet] -quiet

# IP: bd/block1/ip/block1_xlslice_0_3/block1_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block1_xlslice_0_3 || ORIG_REF_NAME==block1_xlslice_0_3} -quiet] -quiet

# XDC: bd/block1/block1_ooc.xdc
